# Generated by Django 4.2.21 on 2025-05-18 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('how_get', models.TextField()),
                ('promocode', models.CharField(blank=True, max_length=64, null=True)),
                ('validity_period', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='static/imgs')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.category')),
                ('partner_description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discounts.partner')),
            ],
        ),
    ]
